name: build-actions
run-name: Build and deploy.
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      API_DOMAIN: resume-api.test.patrickdrew.com
      CYPRESS_BASE_URL: https://resume.test.patrickdrew.com
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::428421847827:role/GitHubActionsRole
          role-session-name: GithubActions
          aws-region: us-east-1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.x'
      - name: Build FrontEnd
        working-directory: ./FrontEnd/src
        run: |
          npm ci
          npm run build
          touch out/.nojekyll
          mkdir ../dist
          cp -r ./out/* ../dist
      - name: Build BackEnd
        working-directory: ./BackEnd/src
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet build
          dotnet lambda package --output-package ../dist/function.zip
      - name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          format: syft-text
          output-file: "${{ github.event.repository.name }}-sbom.txt"
      - name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.txt"
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: "${{ github.event.repository.name }}-sbom.txt"
      - name: Deploy
        working-directory: ./Build
        run: | 
          npm install -g aws-cdk
          cdk deploy --require-approval never --context useDockerBundling=false
      - name: Smoke Test
        working-directory: ./FrontEnd/src
        run: |
          npm run smokeTest